apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb-service
  name: influxdb-service
spec:
  ports:
  - name: influxdb-port
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb-deployment

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/.influxdb"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb-deployment
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 32Mi
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb-deployment
  name: influxdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-deployment
  template:
    metadata:
      labels:
        app: influxdb-deployment
    spec:
      containers:
      - image: influxdb-image
        imagePullPolicy: Never
        name: influxdb-image
        volumeMounts:
        - name: influxdb-volume
          mountPath: /root/.influxdb
        ports:
        - containerPort: 3306
      restartPolicy: Always
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
            claimName: influxdb-pvc
