apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-port-ssl
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-deployment
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx-image
        imagePullPolicy: Never
        name: nginx-image
        ports:
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
