apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: wordpress-port
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress-deployment
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress-deployment
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - image: wordpress-image
        imagePullPolicy: Never
        name: wordpress-image
        ports:
        - containerPort: 5050
      restartPolicy: Always
