apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps-service
  name: ftps-service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: ftps-control
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftps-data
    port: 21
    protocol: TCP
    targetPort: 21
  selector:
    app: ftps-deployment
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps-deployment
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-deployment
  template:
    metadata:
      labels:
        app: ftps-deployment
    spec:
      containers:
      - image: ftps-image
        imagePullPolicy: Never
        name: ftps-image
        ports:
        - containerPort: 20
          protocol: TCP
        - containerPort: 21
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
