apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps-deployment
  name: ftps-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ftps-depl
  template:
    metadata:
      labels:
        app: ftps-depl
    spec:
      containers:
      - image: ftps-image:latest
        imagePullPolicy: Never 
        name: ftps-container
        ports:
        - containerPort: 20
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
